# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20160723_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedata',
            name='base_attack',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='base_capture_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='base_defense',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='base_flee_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='base_stamina',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='candy',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='evolution',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='picture',
            field=models.ImageField(blank=True, default=0, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='poke_id',
            field=models.BigIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='type1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokedata',
            name='type2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
