# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20160723_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedata',
            name='poke_id',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='individual_id',
            field=models.BigIntegerField(),
        ),
    ]
