# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20160723_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedata',
            name='name',
            field=models.CharField(default='Missingno', max_length=42),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
