# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20160723_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=42)),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.ItemData'),
        ),
    ]
