# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20160723_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item',
            new_name='item_data',
        ),
    ]
